---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/usernames.yml
  label: usernames
- type: directory
  path: _people
  label: People
  create: documents
  match: "**/*"
- type: jekyll-pages
  label: Main Pages (non-blog)
  create: all
- type: jekyll-posts
  label: Blog Posts
  create: all
  templates:
  - press-and-education
upload_dir: assets/images
public_path: https://koobifora.org/assets/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
